# Crowdin Configuration for ICD-10 Mobile Assistant
# Free for open-source projects: https://crowdin.com/page/open-source-project-setup-request

project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

preserve_hierarchy: true

files:
  # Main app translations
  - source: /src/i18n/locales/en.json
    translation: /src/i18n/locales/%two_letters_code%.json
    languages_mapping:
      two_letters_code:
        ar: ar
        es: es
        fr: fr
        hi: hi
        pt: pt
        sw: sw
        zh-CN: zh
        de: de
        ja: ja
        ko: ko
        ru: ru
        it: it
        nl: nl
        tr: tr
        vi: vi
    update_option: update_as_unapproved
    type: auto

  # Documentation translations (optional - for future)
  # - source: /docs/en/**/*.md
  #   translation: /docs/%two_letters_code%/**/%original_file_name%
  #   languages_mapping:
  #     two_letters_code:
  #       es: es
  #       fr: fr
  #       pt: pt
