// Disclaimer and warning text constants

export const AI_ANALYSIS_DISCLAIMER = `
This analysis is generated by an experimental AI system.
It suggests POSSIBLE conditions for the clinician to consider.
It does NOT provide a medical diagnosis or treatment plan.
The clinician remains fully responsible for all clinical decisions.
`.trim();

export const ASSISTANT_DISCLAIMER = `
This assistant helps with documentation and ICD-10 coding.
It does NOT provide medical diagnoses or clinical decisions.
`.trim();

export const RESEARCH_MODE_BANNER = `
🔬 Research Mode – For educational and research purposes only.
Not approved for clinical use.
`.trim();

export const HIGH_RISK_WARNING = `
This is NOT a diagnosis. Please urgently review the patient 
and follow your local clinical guidelines.
`.trim();

export const ENCOUNTER_AI_DISCLAIMER = `
AI analysis is experimental and for research purposes only.
Always verify all suggestions against clinical findings.
`.trim();
